### ISSUE TITLE
Can not install in Fedora 25

### ISSUE THREAD

**Issue by murpholinox** [jamiemcg/Remarkable#100]
i click on the rpm, then I choose open with Software center-> then Install (I provide my password, the installation completes) then Launch...And A notification pops up ("Oops something went wrong") (I guess because the notification disappear almost immediately) .

If I try from the terminal I get:
```
remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.5/site-packages/gi/__init__.py", line 122, in require_version
    (namespace, version))
ValueError: Namespace WebKit not available for version 3.0
```

**Comment by jimkp** [comment]
You can install from the command line with dnf install "path-to-rpm" but it still doesn't run.
```
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib64/python3.5/site-packages/gi/__init__.py", line 106, in require_version
    (namespace, version))
ValueError: Namespace GtkSource not available for version 3.0
```

**Comment by murpholinox** [comment]
so...not very helpful. 
I can not add anything ....except that it used to work in chapeau 24

**Comment by jimkp** [comment]
Looking at [this issue](https://github.com/jamiemcg/Remarkable/issues/88) I found the missing package is gtksourceview3 so `dnf install gtksourceview3` is required.

**Comment by murpholinox** [comment]
```
dnf  fmp  ~  su
Contraseña: 
 root  /  home  fmp  dnf install gtksourceview3
Última comprobación de caducidad de metadatos hecha hace 0:52:42, el Sat Jan 28 21:58:31 2017.
El paquete gtksourceview3-3.22.2-1.fc25.x86_64 ya se encuentra instalado, omitiendo.
Dependencias resueltas.
Nada por hacer.
¡Listo!
 root  /  home  fmp  remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.5/site-packages/gi/__init__.py", line 122, in require_version
    (namespace, version))
ValueError: Namespace WebKit not available for version 3.0
 root  /  home  fmp  exit
 fmp  ~  remarkable
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.5/site-packages/gi/__init__.py", line 122, in require_version
    (namespace, version))
ValueError: Namespace WebKit not available for version 3.0
 fmp  ~  

```

Nope

**Comment by jimkp** [comment]
I didn't see that error but I have webkitgtk.x86_64, webkitgtk3.x86_64, webkitgtk4.x86_64,
webkitgtk4-jsc.x86_64 and webkitgtk4-plugin-process-gtk2.x86_64  installed.

**Comment by spartan223193** [comment]
Running `sudo dnf install webkitgtk3.x86_64`  and `sudo dnf install gtksourceview3` based on the post from @jimkp worked for me on Fedora 25

**Comment by tleb** [comment]
Same here as @spartan223193, thanks @jimkp. I think this issue can be closed.

**Comment by dodona2** [comment]
murpholinox is right, as there is no webkitgtk3 in Fedora 27 anymore. Any idea?
