### ISSUE TITLE
ValueError: Namespace Gtk not available

### ISSUE THREAD

**Issue by brylie** [jamiemcg/Remarkable#102]
When running Remarkable on Ubuntu 16.o4, with Python 3, the program fails to start. The following traceback is visible in console:

```python
 Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 27, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**Comment by jamiemcg** [comment]
How are you trying to launch Remarkable?

**Comment by brylie** [comment]
I am not sure how I was launching the program. I just tried to reproduce with the .deb installation and typing `remarkable` in the command prompt. Things work fine now.

**Comment by al3xy** [comment]
File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available


i have almost the same problem, under debian, with version 1.87. any tip?
