### ISSUE TITLE
Python error with Ubuntu Mate 16.10: " No Module named 'styles' "

### ISSUE THREAD

**Issue by ericbarnhill** [jamiemcg/Remarkable#104]
Hi, 

Cloning into the repo, then running the executable gives
````
Traceback (most recent call last):
  File "bin/remarkable", line 65, in <module>
    import remarkable
  File "/home/ericbarnhill/Documents/code/Remarkable/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/home/ericbarnhill/Documents/code/Remarkable/remarkable/RemarkableWindow.py", line 39, in <module>
    import styles
ImportError: No module named 'styles'

````

Doesn't run. What am I missing?

**Comment by jamiemcg** [comment]
You cannot just run the executable. The required libraries won't be available from $PATH. You have to install the debian first.
