### ISSUE TITLE
AttributeError: 'TextBuffer' object has no attribute 'set_language'

### ISSUE THREAD

**Issue by Kroid** [jamiemcg/Remarkable#109]
After install on Fedora 20:

```
$ remarkable 
*Spellchecking not enabled.
*To enable spellchecking install pygtkspellcheck
*https://pypi.python.org/pypi/pygtkspellcheck/
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 49, in main
    window = RemarkableWindow.RemarkableWindow()
  File "/usr/lib/python3/dist-packages/remarkable_lib/Window.py", line 54, in __new__
    new_object.finish_initializing(builder)
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 105, in finish_initializing
    self.text_buffer.set_language(self.lang_manager.get_language('markdown'))
AttributeError: 'TextBuffer' object has no attribute 'set_language'
```

**Comment by Kroid** [comment]
Why you close issue?

**Comment by jhoelzl** [comment]
I have the same error on application startup using Ubuntu 14.04. Any suggestions?
