### ISSUE TITLE
Installing Remarkable 1.87 on Ubuntu 16.04 LTS - AttributeError: module 'markdown' has no attribute 'markdown'

### ISSUE THREAD

**Issue by mthompson** [jamiemcg/Remarkable#145]
For anyone who encounters installation issues after downloading remarkable from `http://remarkableapp.github.io/linux.html`, I've outlined the issue and provided a workaround as shown below -

#### Install 
```bash
sudo dpkg -isudo dpkg -i remarkable_1.87_all.deb
Selecting previously unselected package remarkable.
(Reading database ... 368119 files and directories currently installed.)
Preparing to unpack .../remarkable_1.87_all.deb ...
Unpacking remarkable (1.87) ...
dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on python3-markdown; however:
  Package python3-markdown is not installed.
 remarkable depends on wkhtmltopdf; however:
  Package wkhtmltopdf is not installed.

dpkg: error processing package remarkable (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160415-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for libglib2.0-0:i386 (2.48.2-0ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.48.2-0ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 remarkable
```

#### Launching `remarkable` from the commandline you'll get the following error message:

```bash
remarkable 
*Spellchecking not enabled.
*To enable spellchecking install pygtkspellcheck
*https://pypi.python.org/pypi/pygtkspellcheck/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 1437, in update_live_preview
    html_middle = markdown.markdown(text, self.default_extensions)
AttributeError: module 'markdown' has no attribute 'markdown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 1440, in update_live_preview
    html_middle = markdown.markdown(text, extensions =self.safe_extensions)
AttributeError: module 'markdown' has no attribute 'markdown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 49, in main
    window = RemarkableWindow.RemarkableWindow()
  File "/usr/lib/python3/dist-packages/remarkable_lib/Window.py", line 54, in __new__
    new_object.finish_initializing(builder)
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 142, in finish_initializing
    self.update_live_preview(self)
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 1442, in update_live_preview
    html_middle = markdown.markdown(text)
AttributeError: module 'markdown' has no attribute 'markdown'
```

#### Installing the following packages will fix the above error and allow `remarkable` to run successfully
- apt install python3-markdown wkhtmltopdf

```bash
sudo apt-get install python3-markdown wkhtmltopdf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-image-4.4.0-66-generic linux-image-extra-4.4.0-66-generic
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  python-markdown-doc
Recommended packages:
  python3-pygments python3-yaml
The following NEW packages will be installed:
  python3-markdown wkhtmltopdf
0 upgraded, 2 newly installed, 0 to remove and 284 not upgraded.
1 not fully installed or removed.
Need to get 239 kB of archives.
After this operation, 1,253 kB of additional disk space will be used.
Get:1 http://za.archive.ubuntu.com/ubuntu xenial/universe amd64 python3-markdown all 2.6.6-1 [52.4 kB]
Get:2 http://za.archive.ubuntu.com/ubuntu xenial/universe amd64 wkhtmltopdf amd64 0.12.2.4-1 [187 kB]
Fetched 239 kB in 1s (138 kB/s)      
Selecting previously unselected package python3-markdown.
(Reading database ... 368191 files and directories currently installed.)
Preparing to unpack .../python3-markdown_2.6.6-1_all.deb ...
Unpacking python3-markdown (2.6.6-1) ...
Selecting previously unselected package wkhtmltopdf.
Preparing to unpack .../wkhtmltopdf_0.12.2.4-1_amd64.deb ...
Unpacking wkhtmltopdf (0.12.2.4-1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up python3-markdown (2.6.6-1) ...
Setting up wkhtmltopdf (0.12.2.4-1) ...
Setting up remarkable (1.87) ...
```

**Comment by jamiemcg** [comment]
This not a bug. `dpkg -i` does not attempt to install any dependencies of a package. You must either install the dependencies yourself (as above) or use a package manager that automatically resolves and installs dependencies for you (for example `GDebi`).
