### ISSUE TITLE
Add Spelling feauture (multilang) with spelling proposition on the right click

### ISSUE THREAD

**Issue by Paviluf** [jamiemcg/Remarkable#15]
Hello,

It will be very great if a Spelling feature, that support multilang with spelling proposition on the right click, can be add to Remarkable.

Thanks !

**Comment by jamiemcg** [comment]
Spellchecking in Remarkable is available by installing [pygtkspellcheck](https://pypi.python.org/pypi/pygtkspellcheck/) but seems to not be working recently, I will investigate. 

---

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtkspellcheck/spellcheck.py", line 496, in _click_move_button
    if self._deferred_check:  self._check_deferred_range(True)
AttributeError: 'SpellChecker' object has no attribute '_deferred_check'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtkspellcheck/spellcheck.py", line 154, in <lambda>
    self._view.connect('populate-popup', lambda entry, menu: self._extend_menu(menu))
  File "/usr/lib/python3/dist-packages/gtkspellcheck/spellcheck.py", line 452, in _extend_menu
    if not self._enabled:
AttributeError: 'SpellChecker' object has no attribute '_enabled'

**Comment by Paviluf** [comment]
I didn't know that. Thanks !

I understand that it should not work for now but in order to test it I tried to install pygtkspellcheck on Fedora 24. Since pygtkspellcheck don't seem to be in the repo I installed it like that :
```
$ sudo pip install --upgrade pip
$ sudo pip install pyenchant Sphinx pygtkspellcheck
```
But when I launch remarkable from the terminal it don't seem to be aware that is installed :
```
*Spellchecking not enabled.
*To enable spellchecking install pygtkspellcheck
*https://pypi.python.org/pypi/pygtkspellcheck/
```

**Comment by jamiemcg** [comment]
Thanks! I will look into it.

**Comment by marc0der** [comment]
Hi, I'm loving remarkable, but really missing having that spellcheck. Any progress on this yet?

**Comment by Paviluf** [comment]
Hello,

I hope you didn't forget :)

**Comment by Paviluf** [comment]
Hello,

Any progress ? Thanks !

**Comment by kapad** [comment]
Any progress. I don't want to stop using Remarkable, but I really miss spell check

**Comment by AlistairDoswald** [comment]
Hello, 
it seems to be linked to the version of python used (see [this old issue](https://github.com/remarkableapp/Remarkable-Linux/issues/20)).

I saw that my default `pip` was using python 2.7, so I installed `pygtkspellcheck` with 
```
$ sudo pip3.6 install pyenchant Sphinx pygtkspellcheck
```
And I now have spell checking in Remarkable.

... either that or the issue has been since been corrected and calling just `pip` would have worked anyway. I didn't go into any additional tests.

**Comment by kapad** [comment]
@AlistairDoswald I keep getting an error when I run that command. 

```
The directory '/home/<username>/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/<username>/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyenchant
  Downloading pyenchant-2.0.0.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 254kB/s 
Collecting Sphinx
  Downloading Sphinx-1.6.5-py2.py3-none-any.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 822kB/s 
Collecting pygtkspellcheck
  Downloading pygtkspellcheck-4.0.5.tar.gz (167kB)
    100% |████████████████████████████████| 174kB 120kB/s 
    Complete output from command python setup.py egg_info:
    build_sphinx command is unavailable, please install Sphinx to solve this
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uoy1xxsz/pygtkspellcheck/setup.py", line 44, in <module>
        import gtkspellcheck
      File "/tmp/pip-build-uoy1xxsz/pygtkspellcheck/src/gtkspellcheck/__init__.py", line 52, in <module>
        from gtkspellcheck.spellcheck import (SpellChecker, NoDictionariesFound,
      File "/tmp/pip-build-uoy1xxsz/pygtkspellcheck/src/gtkspellcheck/spellcheck.py", line 26, in <module>
        import enchant
    ImportError: No module named 'enchant'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uoy1xxsz/pygtkspellcheck/
```

**Comment by kapad** [comment]
I'm using python 3.5.3 and pip 9.0.1

**Comment by kapad** [comment]
[This](https://github.com/remarkableapp/Remarkable-Linux/issues/20#issuecomment-186615548) worked for me though. 

```
sudo apt-get install python3-gtkspellcheck
```

**Comment by AlistairDoswald** [comment]
I think that for Debian-based installations, `apt-get install python3-gtkspellcheck` is the solution.

However,  I'm under Fedora 26 and I couldn't find a `dnf` equivalent. For Fedora (and probably other rpm based distributions) `pip3 install pyenchant Sphinx pygtkspellcheck` should be tried. For me it worked with pip 9.0.1 and python 3.6.2.

**Comment by kapad** [comment]
Yes. Must be the difference between package names in apt and fedora.

Though, pip should be universal and not affected by distribution. For some
reason though, pip failed for me.

**Comment by kevquirk** [comment]
This worked for me:
``sudo apt-get install python3-gtkspellcheck

**Comment by kiey** [comment]
sudo apt-get install python3-gtkspellcheck
did the trick,
also, remember to install the language pack for the desired language in your system in case you want another one apart from the one your system is set
