### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by micrub** [jamiemcg/Remarkable#156]
```
➜ sudo dpkg -i ~/Downloads/remarkable_1.87_all.deb
➜ remarkable
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 29, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'
➜ sudo pip install bs4
➜ remarkable          
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 29, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'
➜ pip -V  
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
➜ python -V
Python 2.7.6
➜ cat /etc/issue
Ubuntu 14.04.5 LTS \n \l
```

**Comment by tleb** [comment]
`/usr/lib/python3` but you install bs4 using Python 3's pip ; you need to use `pip3`.

**Comment by LuxGiammi** [comment]
tleb's fix didn't work for me. The utility GDebi run for me these commands when I tried to install the .deb package and then they worked fine.:
- apt-get install python3-markdown
- apt-get install wkhtmltopdf
- apt-get install python3-bs4
