### ISSUE TITLE
install remarkable in ubuntu 16.04 failed

### ISSUE THREAD

**Issue by oska874** [jamiemcg/Remarkable#18]
I try to install reamarkable from github ,but failed : 

```
sudo python2.7 setup.py install
/workspace/ccache/download/Remarkable-master/remarkable_lib/Builder.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gtk # pylint: disable=E0611
running install
running build
running build_py
running build_scripts
running build_i18n
intltool-update -p -g remarkable
running build_icons
running build_help
running install_lib
running install_scripts
changing mode of /usr/local/bin/remarkable to 775
running install_data
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/remarkable-1.75.egg-info
Writing /usr/local/lib/python2.7/dist-packages/remarkable-1.75.egg-info
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    cmdclass={'install': InstallAndUpdateDataDirectory}
  File "/usr/lib/python2.7/dist-packages/DistUtilsExtra/auto.py", line 100, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 128, in run
    target_data = '/' + os.path.relpath(self.install_data, self.root) + '/'
  File "/usr/lib/python2.7/posixpath.py", line 430, in relpath
    start_list = [x for x in abspath(start).split(sep) if x]
  File "/usr/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/usr/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

```

How to solve this problem ?

**Comment by jamiemcg** [comment]
First, Remarkable is written in Python 3.

Secondly, I don't recommend trying to install Remarkable from the GitHub repository. It is better just to use one of the [premade packages from here](http://remarkableapp.github.io/linux/download.html).

**Comment by oska874** [comment]
I tried python3 ,fail too.
And I trying to download premade remarkable ,but I only get a 72.1KB-deb file,and cannot install.

**Comment by jamiemcg** [comment]
@oska874 
72.1KB is the correct size for the deb file. It has been tested on Ubuntu 16.04. It installs and works as expected. What errors are you getting?

Install it with Ubuntu Software or the terminal as below.

If you have **gdebi** installed:
`sudo gdebi remarkable_1.75_all.deb`

Or else:
`sudo dpkg -i remarkable_1.75_all.deb && sudo apt-get install -f`

**Comment by oska874** [comment]
using python3 shows : 
```
python3 setup.py install
  File "setup.py", line 57
    except (OSError, IOError), e :
                             ^
SyntaxError: invalid syntax
```

run `sudo dpkg -i remarkable_1.75_all.deb` shows:

```
sudo dpkg -i remarkable_1.75_all.deb
(Reading database ... 448471 files and directories currently installed.)
Preparing to unpack remarkable_1.75_all.deb ...
Unpacking remarkable (1.75) over (1.75) ...
dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on python3-markdown; however:
  Package python3-markdown is not installed.
 remarkable depends on gir1.2-webkit-3.0; however:
  Package gir1.2-webkit-3.0 is not installed.
 remarkable depends on wkhtmltopdf; however:
  Package wkhtmltopdf is not installed.

dpkg: error processing package remarkable (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160523-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for libglib2.0-0:amd64 (2.48.1-1~ubuntu16.04.1) ...
No such key 'Gtk/IMModule' in schema 'org.gnome.settings-daemon.plugins.xsettings' as specified in override file '/usr/share/glib-2.0/schemas/50_sogoupinyin.gschema.override'; ignoring override for this key.
Errors were encountered while processing:
```

run `sudo gdebi remarkable_1.75_all.deb` shows : 

```
Setting up remarkable (1.75) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160523-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for libglib2.0-0:amd64 (2.48.1-1~ubuntu16.04.1) ...
No such key 'Gtk/IMModule' in schema 'org.gnome.settings-daemon.plugins.xsettings' as specified in override file '/usr/share/glib-2.0/schemas/50_sogoupinyin.gschema.override'; ignoring override for this key.

```

run `remarkable` shows:

```
Traceback (most recent call last):
  File "/usr/local/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/local/lib/python2.7/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/local/lib/python2.7/dist-packages/remarkable/RemarkableWindow.py", line 34, in <module>
    from urllib.request import urlopen
ImportError: No module named request

```

**Comment by jamiemcg** [comment]
You seem to have a dependency problem, Remarkable can be installed without any issues.

I recommend running:
```
sudo apt-get remove remarkable
sudo apt-get install -f #fix pre-existing dependency error
sudo gdebi remarkable_1.75_all.deb
```

**Comment by oska874** [comment]
@jamiemcg It's ok that I remove all remarkable installed (both from deb and source) and reinstall ,it runs ok.
