### ISSUE TITLE
Ubuntu 16.04 LTS - AttributeError running remarkable | from 1.87 deb install (with dependencies)

### ISSUE THREAD

**Issue by fireofearth** [jamiemcg/Remarkable#192]
I installed Remarkable from deb (remarkable_1.87_all.deb) from the main website (https://remarkableapp.github.io/linux/download.html) with all the dependencies suing gdebi

Note I'm running Ubuntu 16.04 LTS

```
$ sudo gdebi remarkable_1.87_all.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Requires the installation of the following packages: python3-markdown python3-pygments python3-yaml wkhtmltopdf 

A free fully featured markdown editor.
 Remarkable is a free fully featured markdown editor. It has a syntax
 like Github flavoured markdown. With it you can write markdown and view
 the changes as you make them in the live preview window. You can export
 your files to a variety of formats. There are multiple styles available
 along with extensive configuration options so you can set it up exactly
 how you like.
Do you want to install the software package? [Y/N]:Y
Fetched 0 B in 0s (0 B/s)                                                                                                                                         
Selecting previously unselected package python3-markdown.
(Reading database ... 437824 files and directories currently installed.)
Preparing to unpack .../python3-markdown_2.6.6-1_all.deb ...
Unpacking python3-markdown (2.6.6-1) ...
Selecting previously unselected package python3-pygments.
Preparing to unpack .../python3-pygments_2.1+dfsg-1_all.deb ...
Unpacking python3-pygments (2.1+dfsg-1) ...
Selecting previously unselected package python3-yaml.
Preparing to unpack .../python3-yaml_3.11-3build1_amd64.deb ...
Unpacking python3-yaml (3.11-3build1) ...
Selecting previously unselected package wkhtmltopdf.
Preparing to unpack .../wkhtmltopdf_0.12.2.4-1_amd64.deb ...
Unpacking wkhtmltopdf (0.12.2.4-1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up python3-markdown (2.6.6-1) ...
Setting up python3-pygments (2.1+dfsg-1) ...
Setting up python3-yaml (3.11-3build1) ...
Setting up wkhtmltopdf (0.12.2.4-1) ...
Selecting previously unselected package remarkable.
(Reading database ... 438087 files and directories currently installed.)
Preparing to unpack remarkable_1.87_all.deb ...
Unpacking remarkable (1.87) ...
Setting up remarkable (1.87) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for libglib2.0-0:i386 (2.48.2-0ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.48.2-0ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
```

However, when I attempt to run I get the error:

```bash
$ remarkable
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 29, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
```

My python3 version is 3.5.2

**Comment by manankalra** [comment]
I'm facing the same issue. Help needed!

**Comment by jamiemcg** [comment]
@CloudIcarus @manankalra  Is BeautifulSoup 4 installed and if not, does installing it fix your issues?


-------

`sudo apt-get install python3-bs4`

**Comment by josefstr** [comment]
I could solve it with:
```
pip install --upgrade beautifulsoup4
pip install --upgrade html5lib
```

**Comment by ericd13** [comment]
I get same problem
installing beautifulsoup gives an error too : 

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dbzx2s8y/beautifulsoup/
```

**Comment by TeresaChou** [comment]
same problem too! Still have the same error after upgrading beautifulsoup4 and html5lib
