### ISSUE TITLE
Remarkable won't open with Fedora 27

### ISSUE THREAD

**Issue by murpholinox** [jamiemcg/Remarkable#231]
```
[root@eva Downloads]# dnf install remarkable-1.87-1.rpm 
Last metadata expiration check: 0:53:42 ago on Mon 08 Jan 2018 12:22:19 PM CST.
Dependencies resolved.
================================================================================
 Package                  Arch     Version                 Repository      Size
================================================================================
Installing:
 remarkable               noarch   1.87-1                  @commandline    90 k
Installing dependencies:
 python3-beautifulsoup4   noarch   4.6.0-2.fc27            fedora         178 k
 python3-lxml             x86_64   4.1.1-1.fc27            updates        1.4 M
 python3-webencodings     noarch   0.5.1-3.fc27            fedora          25 k
 wkhtmltopdf              x86_64   0.12.4-1.fc27           updates        206 k
Installing weak dependencies:
 python3-cssselect        noarch   0.9.2-5.fc27            fedora          39 k
 python3-html5lib         noarch   1:0.999999999-3.fc27    fedora         213 k

Transaction Summary
================================================================================
Install  7 Packages

Total size: 2.1 M
Total download size: 2.0 M
Installed size: 7.6 M
Is this ok [y/N]: y
Downloading Packages:
(1/6): wkhtmltopdf-0.12.4-1.fc27.x86_64.rpm     165 kB/s | 206 kB     00:01    
(2/6): python3-beautifulsoup4-4.6.0-2.fc27.noar 126 kB/s | 178 kB     00:01    
(3/6): python3-cssselect-0.9.2-5.fc27.noarch.rp  36 kB/s |  39 kB     00:01    
(4/6): python3-webencodings-0.5.1-3.fc27.noarch  51 kB/s |  25 kB     00:00    
(5/6): python3-html5lib-0.999999999-3.fc27.noar 147 kB/s | 213 kB     00:01    
(6/6): python3-lxml-4.1.1-1.fc27.x86_64.rpm     278 kB/s | 1.4 MB     00:04    
--------------------------------------------------------------------------------
Total                                           332 kB/s | 2.0 MB     00:06     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : python3-webencodings-0.5.1-3.fc27.noarch               1/7 
  Installing       : python3-lxml-4.1.1-1.fc27.x86_64                       2/7 
  Installing       : python3-beautifulsoup4-4.6.0-2.fc27.noarch             3/7 
  Installing       : wkhtmltopdf-0.12.4-1.fc27.x86_64                       4/7 
  Running scriptlet: wkhtmltopdf-0.12.4-1.fc27.x86_64                       4/7 
  Installing       : remarkable-1.87-1.noarch                               5/7 
  Installing       : python3-html5lib-1:0.999999999-3.fc27.noarch           6/7 
  Installing       : python3-cssselect-0.9.2-5.fc27.noarch                  7/7 
  Running scriptlet: python3-cssselect-0.9.2-5.fc27.noarch                  7/7 
Running as unit: run-r038341b6c31c48e688b2559e66c4624b.service
  Verifying        : remarkable-1.87-1.noarch                               1/7 
  Verifying        : python3-beautifulsoup4-4.6.0-2.fc27.noarch             2/7 
  Verifying        : wkhtmltopdf-0.12.4-1.fc27.x86_64                       3/7 
  Verifying        : python3-lxml-4.1.1-1.fc27.x86_64                       4/7 
  Verifying        : python3-cssselect-0.9.2-5.fc27.noarch                  5/7 
  Verifying        : python3-html5lib-1:0.999999999-3.fc27.noarch           6/7 
  Verifying        : python3-webencodings-0.5.1-3.fc27.noarch               7/7 

Installed:
  remarkable.noarch 1.87-1                                                      
  python3-cssselect.noarch 0.9.2-5.fc27                                         
  python3-html5lib.noarch 1:0.999999999-3.fc27                                  
  python3-beautifulsoup4.noarch 4.6.0-2.fc27                                    
  python3-lxml.x86_64 4.1.1-1.fc27                                              
  python3-webencodings.noarch 0.5.1-3.fc27                                      
  wkhtmltopdf.x86_64 0.12.4-1.fc27                                              

Complete!
[root@eva Downloads]# exit
[murph@eva ~]$ remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```

Ps 1 This is a new installation. 

Ps 2 In a previous issue ([100](https://github.com/jamiemcg/Remarkable/issues/100)), a couple of packages solved the problem for a couple of guys, not for me.  I try to install those packages but ...
```
[root@eva murph]# dnf install webkitgtk3
Last metadata expiration check: 0:47:32 ago on Mon 08 Jan 2018 12:22:19 PM CST.
No match for argument: webkitgtk3
Error: Unable to find a match
[root@eva murph]# dnf install webkitgtk
Last metadata expiration check: 0:47:41 ago on Mon 08 Jan 2018 12:22:19 PM CST.
No match for argument: webkitgtk
Error: Unable to find a match
[root@eva murph]# dnf install gtksourceview3
Last metadata expiration check: 0:53:08 ago on Mon 08 Jan 2018 12:22:19 PM CST.
Package gtksourceview3-3.24.6-1.fc27.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.

```
  One can not be found and the other I already have....

**Comment by misaelnieto** [comment]
On F26 `webkitgtk3` did the trick. Also curious how to make it work on F27.

**Comment by dvdmuckle** [comment]
I believe the package would have to be built for Fedora 27, as opposed to created from a .deb.

**Comment by dodona2** [comment]
it fails to run directly out of git, as expected. Its clearly the webkit**3** dependency. is 3 really needed?

**Comment by leifmadsen** [comment]
WebKit GTK3 is no longer available for Fedora 27 and later (it was removed). Remarkable would need to be made to work with WebKit GTK4.

**Comment by Bonsitar** [comment]
Exactly right.
I 'm agree with @dvdmuckle about .rpm package.
But on the other hand maintainers can provide flatpak packages for all modern distro instead of having all these issue to make packages for different distros!

**Comment by Frankstar** [comment]
so ... this never got fixed ?
