### ISSUE TITLE
Error in decoding UTF-8 characters 

### ISSUE THREAD

**Issue by jmichelet** [jamiemcg/Remarkable#241]
Trying to open a file that contains some UTF-8 characters, the GUI freezes, and the console reports that error :
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 356, in on_menuitem_open_activate
    self.open(self)
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 382, in open
    text = file.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 366: ordinal not in range(128)

OS : Ubuntu 16.04.3 LTS
Version : 1.87
Language env. variables
  LANG=en_US.UTF-8
  GDM_LANG=en_US
  LANGUAGE=en_US:en

**Comment by Kyle0122** [comment]
I met the same problem!

**Comment by Alex-Kent** [comment]
@Kyle0122 @ymarcov

Here's a patch that'll get UTF-8 working.  Not heavily tested but load and save seem to work correctly.

Uncompress the [attached file](https://github.com/jamiemcg/Remarkable/files/3031491/RemarkableWindow.py.patch.gz) (perhaps with `gunzip RemarkableWindow.py.patch.gz`) and save it to `/tmp/RemarkableWindow.py.patch`

To test this patch, go to the directory containing `RemarkableWindow.py` (possibly 
`/usr/lib/python3/dist-packages/remarkable/`) and run:\
`sudo patch --dry-run -p1 -i /tmp/RemarkableWindow.py.patch`

If no errors appear, apply the patch by running:\
`sudo patch -p1 -i /tmp/RemarkableWindow.py.patch`

This patch was generated with:\
`diff -c RemarkableWindow.py patched/RemarkableWindow.py`
