### ISSUE TITLE
Centos7 install - unable to install RPM missing deps 

### ISSUE THREAD

**Issue by morgancoxuk** [jamiemcg/Remarkable#250]
Hi.

I have been really liking using remarkable on my kde neon workstation (based on ubuntu 16.04).

However I have one workstation with Centos7 - I cannot install the RPM as there are package dependencies needed which are not available for the platform

i.e

- python3-beautifulsoup4
- python3-markdown
- wkhtmltopdf

Has anyone else managed to install this in Centos7/Rhel7 ?

**Comment by morgancoxuk** [comment]
No unfortunately ..

In the end I used 'atom' on rhel7..

**Comment by mountainbrother** [comment]
i run into the same problem Centos 7 ? do we have a workaround ?

**Comment by jordanenglish** [comment]
I was having the same issue, but was able to find that the package dependencies were just named incorrectly. Although, even after installing the correct packages it appears the dependencies still fail.


```
$ sudo yum install remarkable-1.87-1.rpm
Loaded plugins: fastestmirror, langpacks
Examining remarkable-1.87-1.rpm: remarkable-1.87-1.noarch
Marking remarkable-1.87-1.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package remarkable.noarch 0:1.87-1 will be installed
--> Processing Dependency: python3-beautifulsoup4 for package: remarkable-1.87-1.noarch
Loading mirror speeds from cached hostfile
 * base: linux.cc.lehigh.edu
 * epel: fedora.mirrors.pair.com
 * extras: mirror.jaleco.com
 * rpmfusion-free-updates: mirror.math.princeton.edu
 * updates: linux.cc.lehigh.edu
--> Processing Dependency: python3-markdown for package: remarkable-1.87-1.noarch
--> Finished Dependency Resolution
Error: Package: remarkable-1.87-1.noarch (/remarkable-1.87-1)
           Requires: python3-markdown
Error: Package: remarkable-1.87-1.noarch (/remarkable-1.87-1)
           Requires: python3-beautifulsoup4
 You could try using --skip-broken to work around the problem
```
These failures are even after installing the following:

```
$ sudo yum info python34-markdown wkhtmltopdf python-beautifulsoup
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: linux.cc.lehigh.edu
 * epel: kdeforge2.unl.edu
 * extras: linux.cc.lehigh.edu
 * rpmfusion-free-updates: mirror.math.princeton.edu
 * updates: linux.cc.lehigh.edu
Installed Packages
Name        : python34-markdown
Arch        : noarch
Version     : 2.4.1
Release     : 2.el7
Size        : 804 k
Repo        : installed
From repo   : epel
Summary     : Markdown implementation in Python
URL         : http://packages.python.org/Markdown/
License     : BSD
Description : This is a Python implementation of John Gruber's Markdown. It is
            : almost completely compliant with the reference implementation, though
            : there are a few known issues.

Name        : wkhtmltopdf
Arch        : x86_64
Version     : 0.12.1
Release     : 1.el7
Size        : 722 k
Repo        : installed
From repo   : epel
Summary     : Simple shell utility to convert html to pdf
URL         : http://wkhtmltopdf.org/
License     : GPLv3+
Description : Simple shell utility to convert html to pdf using the webkit
            : rendering engine, and qt.

Available Packages
Name        : python-BeautifulSoup
Arch        : noarch
Epoch       : 1
Version     : 3.2.1
Release     : 7.el7
Size        : 44 k
Repo        : epel/x86_64
Summary     : HTML/XML parser for quick-turnaround applications like screen-scraping
URL         : http://www.crummy.com/software/BeautifulSoup/
License     : BSD
Description : Beautiful Soup is a Python HTML/XML parser designed for quick
            : turnaround projects like screen-scraping. Three features make it
            : powerful:
            : 
            : Beautiful Soup won't choke if you give it bad markup.
            : 
            : Beautiful Soup provides a few simple methods and Pythonic idioms for
            : navigating, searching, and modifying a parse tree.
            : 
            : Beautiful Soup automatically converts incoming documents to Unicode
            : and outgoing documents to UTF-8.
            : 
            : Beautiful Soup parses anything you give it.
            : 
            : Valuable data that was once locked up in poorly-designed websites is
            : now within your reach. Projects that would have taken hours take only
            : minutes with Beautiful Soup.
```
Anyone have suggestions for an editor that is CentOS friendly?

**Comment by jakub-olczyk** [comment]
I have tried using `rpmrebuild` ([man page](https://linux.die.net/man/1/rpmrebuild)) in order to change the spec file to point to the right dependencies. While doing so I have discovered that the RPM is in fact created using [Alien](https://www.tecmint.com/convert-from-rpm-to-deb-and-deb-to-rpm-package-using-alien/). This might explain the wrong dependencies for RPM.

### Steps to reproduce my failed attempt at fixing the rpm

So I tried
```bash
rpmrebuild -pe remarkable-1.87-1.rpm #as root
```
an changed the `python-markdown` to `python34-markdown`.
After test install I found a missing dependancy... for GTK package. 
```python
import gi # from file /usr/lib/python3/dist-packages/remarkable/__init__.py
```
 So I installed it manually
```
yum -y install python34-gobject
```
Afterwards the problem was missing python3-beautifulsoup4. I think the program might work if it looked for the python-beautifulsoup4 (which is installed as a dependency), but as the stack trace suggest
```bash
$ remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 29, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'
```
it isn't looking for packages in `/usr/lib/python2.7/` .
As I couldn't find RPM for python34-beautifulsoup4 I gave up on using this application on Scientific Linux 7.6 :(
I hope this might be of help for the maintainer. I also can help with packaging a real RPM and not using a conversion tool.
