### ISSUE TITLE
Remarkable doesn't start and show after installing with .rpm package! [bug]

### ISSUE THREAD

**Issue by Bonsitar** [jamiemcg/Remarkable#253]
```
>>> remarkable
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```
Installed with .rpm package in: https://remarkableapp.github.io/linux/download.html
on Fedora Gnome 27.
Need more details? feel free to contact me!
Thanks.

**Comment by cognusion** [comment]
Same. Installed various python3 webkit mods, and same.

**Comment by Bonsitar** [comment]
Thanks for your reply!
