### ISSUE TITLE
install issue in fedora 28

### ISSUE THREAD

**Issue by lucodealethea** [jamiemcg/Remarkable#257]
/usr/bin/remarkable
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

**Comment by lucodealethea** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1375843

> The webkitgtk3 package will be removed from rawhide after Fedora 26 is
> branched due to the high number of unfixed security vulnerabilities. You
> must remove this dependency or your package will not be present in Fedora 27.

**Comment by jotak** [comment]
So what's the recommended solution? (other than installing a dependency full of vulnerabilities?)

**Comment by neteler** [comment]
FWIW, here I maintain the Fedora RPM of remarkable:

https://copr.fedorainfracloud.org/coprs/neteler/remarkable/
