### ISSUE TITLE
Starting Remarkable with run.sh fails due to "ValueError: Namespace WebKit not available"

### ISSUE THREAD

**Issue by krichter722** [jamiemcg/Remarkable#296]
On Ubuntu 19.04 the start with `run.sh` fails due to

```
> ./run.sh 
Traceback (most recent call last):
  File "/mnt/data/sources/Remarkable/bin/remarkable", line 65, in <module>
    import remarkable
  File "/mnt/data/sources/Remarkable/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/mnt/data/sources/Remarkable/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```

which is probably causes by incompatibility with WebKit 4.x. On Ubuntu 19.04 WebKit 3.x is no longer available, other distributions where this is the case might follow.

Existing issues https://github.com/jamiemcg/Remarkable/issues/279 and https://github.com/jamiemcg/Remarkable/issues/219 deal with the problem on Fedora, but only propose to install WebKit 3.x bindings as solution.

experienced with v1.87-27-gda0d88c

**Comment by cabe7** [comment]
Same issue trying to install on 19.04 via .deb

gir1.2-webkit-3.0 dependency is unavailable

**Comment by en-lofty** [comment]
Same issue on Ubuntu 19.04

Journal: 

> remarkable: Depends: gir1.2-webkit-3.0 but it is not installable

**Comment by ignaciovidalfranco** [comment]
```
me@mycomputer:~/Downloads$ sudo dpkg -i remarkable_1.87_all.deb 
Seleccionando el paquete remarkable previamente no seleccionado.
(Leyendo la base de datos ... 240934 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar remarkable_1.87_all.deb ...
Desempaquetando remarkable (1.87) ...
**dpkg: problemas de dependencias impiden la configuración de remarkable:
 remarkable depende de gir1.2-webkit-3.0; sin embargo:
  El paquete `gir1.2-webkit-3.0' no está instalado.**

dpkg: error al procesar el paquete remarkable (--install):
 problemas de dependencias - se deja sin configurar
Procesando disparadores para mime-support (3.60ubuntu1) ...
Procesando disparadores para gnome-menus (3.32.0-1ubuntu1) ...
Procesando disparadores para desktop-file-utils (0.23-4ubuntu1) ...
Procesando disparadores para libglib2.0-0:amd64 (2.60.0-1ubuntu0.1) ...
Procesando disparadores para hicolor-icon-theme (0.17-2) ...
Se encontraron errores al procesar:
 remarkable
```
Sorry for the Spanish, but I think the error message is quite understandable.

**Comment by ledav-net** [comment]
Same error on Fedora 28 with the RPM package:

```text
$ remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```

**Comment by m273d15** [comment]
I had the same issue and was unable to install the `gir1.2-webkit-3.0 dependency`, but `gir1.2-webkit2-4.0` was installed. After changing remarkable [`WebKit` to `WebKit2`](https://github.com/m273d15/Remarkable/commit/034580704f22acf8a1ebd889ca1911ab2b8891d9) the editor works with the `run.sh`.

**Comment by Deadolus** [comment]
Fixed in https://github.com/jamiemcg/Remarkable/pull/314
Alternatively you might consider using the snap I created for https://github.com/jamiemcg/Remarkable/pull/317: 
`sudo snap install remarkable `

**Comment by hhlp** [comment]
I install it via flatpak:

flatpak install com.remarkable.reMarkable

Regards.,
