### ISSUE TITLE
run.sh fails on Clear Linux

### ISSUE THREAD

**Issue by jbhanks** [jamiemcg/Remarkable#304]
```
$~/Downloads/Remarkable-master $ sh run.sh
Traceback (most recent call last):
  File "/home/james/Downloads/Remarkable-master/bin/remarkable", line 65, in <module>
    import remarkable
  File "/home/james/Downloads/Remarkable-master/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/home/james/Downloads/Remarkable-master/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace GtkSource not available for version 3.0
```
I just tried cloning and running run.sh, but I got the above error. I am using Clear Linux with KDE desktop. I tried install the the GTK developer package (devpkg-gtk), but that did not help. Not sure if this is related to my OS or this repo.

**Comment by Deadolus** [comment]
You're probably lacking the package lacking gir1.2-gtksource-3.0

**Comment by jclaveau** [comment]
Dup of #286 probably
