### ISSUE TITLE
ValueError: Namespace WebKit not available

### ISSUE THREAD

**Issue by sevku** [jamiemcg/Remarkable#332]
After installing remarkable via snap store on Ubuntu 18.04, the following Error appears:

```
$ remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

```

**Comment by MichaelTiernan** [comment]
This too seems to be related to #323 and #333
