### ISSUE TITLE
Remarkable does not start on Arch Linux

### ISSUE THREAD

**Issue by ianlet** [jamiemcg/Remarkable#339]
I installed Remarkable with `yay` (from the AUR) but I am unable to run it:
```
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3.8/site-packages/remarkable/__init__.py", line 26, in <module>
    import gi
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

System information:
```
OS: Arch Linux x86_64 
Host: 20KH002HUS ThinkPad X1 Carbon 6th 
Kernel: 5.5.13-arch2-1 
Python: 3.8.2
libffi: 3.3-3
```

**Comment by ianlet** [comment]
Apparently I was missing the latest updates on my system. Updating it seems to have solved the issue.
