### ISSUE TITLE
Remarkable fail to launch on manjaro

### ISSUE THREAD

**Issue by itsDARKSAMA** [jamiemcg/Remarkable#382]
remarkable

Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
AttributeError: module 'remarkable' has no attribute 'main'

**Comment by NA0341** [comment]
same (or similar) issue here:

Installed `remarkable 1.87-6` using Pandoc
-» first output:

```bash
remarkable 
/usr/lib/python3.9/site-packages/pdfkit/source.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.type is 'file':
*Spellchecking not enabled.
*To enable spellchecking install python-gtkspellcheck.
pacman -S --asdeps python-gtkspellcheck
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3.9/site-packages/remarkable/__init__.py", line 49, in main
    window = RemarkableWindow.RemarkableWindow()
  File "/usr/lib/python3.9/site-packages/remarkable_lib/Window.py", line 52, in __new__
    builder = get_builder('RemarkableWindow')
  File "/usr/lib/python3.9/site-packages/remarkable_lib/helpers.py", line 48, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3.9/site-packages/remarkable_lib/Builder.py", line 92, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

Installed missing dependency.
-» second output:

```bash
remarkable
/usr/lib/python3.9/site-packages/pdfkit/source.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.type is 'file':

** (remarkable:22626): WARNING **: 16:15:50.499: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory


** (remarkable:22626): WARNING **: 16:15:50.499: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (remarkable:22626): WARNING **: 16:15:50.500: Error loading plugin: libnuspell.so.4: cannot open shared object file: No such file or directory


** (remarkable:22626): WARNING **: 16:15:50.500: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3.9/site-packages/remarkable/__init__.py", line 49, in main
    window = RemarkableWindow.RemarkableWindow()
  File "/usr/lib/python3.9/site-packages/remarkable_lib/Window.py", line 52, in __new__
    builder = get_builder('RemarkableWindow')
  File "/usr/lib/python3.9/site-packages/remarkable_lib/helpers.py", line 48, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3.9/site-packages/remarkable_lib/Builder.py", line 92, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

**Comment by raffraffraff** [comment]
I'm posting [this workaround](https://github.com/raffraffraff/docker-remarkable) in any of the issues related to installing Remarkable:
However, since [this issue](https://github.com/jamiemcg/Remarkable/issues/378) was is 5 months old and never got an answer, it might be time to find another editor

**Comment by ruchg** [comment]
I have the same issue as the original poster.

Running Cinnamon on Fedora 34

`[ruchg@localhost ~]$ remarkable
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
AttributeError: module remarkable has no attribute main
[ruchg@localhost ~]$ `

Regards.

**Comment by neteler** [comment]
Dirty hack:

```diff
diff -ru /usr/lib/python3.9/site-packages/remarkable_lib/Builder.py.orig /usr/lib/python3.9/site-packages/remarkable_lib/Builder.py
--- /usr/lib/python3.9/site-packages/remarkable_lib/Builder.py.orig	2021-12-01 23:30:33.036956591 +0100
+++ /usr/lib/python3.9/site-packages/remarkable_lib/Builder.py	2021-12-01 23:30:55.301889319 +0100
@@ -89,7 +89,7 @@
         tree = ElementTree()
         tree.parse(filename)
 
-        ele_widgets = tree.getiterator("object")
+        ele_widgets = tree.iter("object")
         for ele_widget in ele_widgets:
             name = ele_widget.attrib['id']
             widget = self.get_object(name)
@@ -111,7 +111,7 @@
             if connections:
                 self.connections.extend(connections)
 
-        ele_signals = tree.getiterator("signal")
+        ele_signals = tree.iter("signal")
         for ele_signal in ele_signals:
             self.glade_handler_dict.update(
             {ele_signal.attrib["handler"]: None})
```

See also dupe in #375

**Comment by gitressa** [comment]
What's a good alternative to Remarkable?

**Comment by NA0341** [comment]
@gitressa wrote:
> What's a good alternative to Remarkable? EDIT: https://github.com/KDE/ghostwriter looks nice.

It's neat but I went away from it since it kept making breaking changes.
Now I only use dedicated professional tools that focus on writing efficiency & content management.
Obsidian for Knowledge Management and Sublime Text & Gedit for quick, efficient Writing (with settings | plugins for session | document index based autocompletion ~ in other words: you only have to write each long word Once).

Ghostwriter is certainly the most Immersive I've come across.
Obsidian with Themes can offer a lot more though ~ and it also supports bg images. It's a whole lot heavier though.

Wait wasn't this ReText in the Past?
If so @jamiemcg please incllude a Note in the Readme to avoid confusion :)
