### ISSUE TITLE
Error running Remarkable on Debian 11

### ISSUE THREAD

**Issue by dahkraf** [jamiemcg/Remarkable#386]
Having installed Remarkable and its dependencies through .deb files, I ran it, but received the an AttributeError error. The following is the full error message:

 `/usr/lib/python3/dist-packages/pdfkit/source.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.type is 'file':
*Spellchecking not enabled.
*To enable spellchecking install pygtkspellcheck
*https://pypi.python.org/pypi/pygtkspellcheck/
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 49, in main
    window = RemarkableWindow.RemarkableWindow()
  File "/usr/lib/python3/dist-packages/remarkable_lib/Window.py", line 52, in __new__
    builder = get_builder('RemarkableWindow')
  File "/usr/lib/python3/dist-packages/remarkable_lib/helpers.py", line 48, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/remarkable_lib/Builder.py", line 92, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
`

Any ideas as to what could be the cause, and if so what to do about it?

**Comment by hyperclock** [comment]
Nothing has happen in 5 years, you probably will not get an answer. I came here for the same reason as you...I geuss I'll look for something THAT WORKS.

What's really bad is that they are asking for donations on their HP.

**Comment by hyperclock** [comment]
it's not as pretty but works....sudo apt install retext
