### ISSUE TITLE
Remarkable crash on startup: Namespace GtkSource not available for version 3.0

### ISSUE THREAD

**Issue by raffaem** [jamiemcg/Remarkable#388]
Remarkable doesn't even start:

```
$ remarkable
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib64/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 3.0
```

**Comment by zakuArbor** [comment]
You can resolve that error by installing: `sudo dnf install gtksourceview3` but you may get another error complaining about webkit like the following:
```
ValueError: Namespace WebKit not available
```

**source** https://github.com/jamiemcg/Remarkable/issues/368#issuecomment-765736998

**Comment by Alex-Kent** [comment]
For Ubuntu 22.04 running the following (as root) will resolve both the `GtkSource` and `WebKit` issues:

```
apt install libgtksourceview-3.0-1 gir1.2-gtksource-3.0 gir1.2-webkit2-4.1
```
