### ISSUE TITLE
[Opensuse Tumbleweed] RPM package should require typelib-1_0-WebKit-3_0

### ISSUE THREAD

**Issue by junrrein** [jamiemcg/Remarkable#39]
After installing Remarkable (including working around issue #22), remarkable refuses to start:

```
~ $ remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.5/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```

This happens because the package typelib-1_0-WebKit-3_0 isn't installed. After installing it, the program works as expected

**Comment by wanicca** [comment]
````
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/bin/remarkable.py", line 66, in <module>
    remarkable.main()
AttributeError: 'module' object has no attribute 'main'
````

I still have such a problem.
