### ISSUE TITLE
Install fails on Fedora F37

### ISSUE THREAD

**Issue by drmcnelson** [jamiemcg/Remarkable#412]
After a fresh install from the rpm on a fedora 37 system, running remarkable produces the following error:

$ remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace WebKit not available for version 3.0

**Comment by mbuguadouglas** [comment]
Facing a similar issue in Fedora 39.

![Screenshot from 2024-09-27 10-24-03](https://github.com/user-attachments/assets/afeb5c23-117c-41dd-be3a-96d4fcaaf153)

Tried to run the application from both the GUI and the CLI, both fail

**Comment by mbvgua** [comment]
Facing a similar issue in my Fedora 39. Tried to run the program from both my GUI and my CLI but nothing works.

![Screenshot from 2024-09-27 10-24-03](https://github.com/user-attachments/assets/5cec4b74-2637-4e0f-b1e2-acb36ca29a16)

**Comment by neteler** [comment]
FYI - I have built it on Fedora COPR.

Find a working version of 1.95 as a RPM package here:
https://copr.fedorainfracloud.org/coprs/neteler/remarkable/

Installation Instructions

```
dnf copr enable neteler/remarkable 
dnf install remarkable 
```

**Comment by danfe** [comment]
> ValueError: Namespace WebKit not available for version 3.0

The culprit is hardcoded WebKit version (currently 4.1) inside `RemarkableWindow.py` which does not necessarily match the corresponding package in a particular GNU/Linux or *BSD distribution.  Either adjust the version to match the installed WebKitGTK package in your system, or remove needless version requirement (this works as a universal advice).
