### ISSUE TITLE
Building from source - got this error.

### ISSUE THREAD

**Issue by gurditsbedi** [jamiemcg/Remarkable#67]
I want to use a virtualenv to test application but i am getting error while building it from source.

``` python
ERROR: Python module gi not found
ERROR: Python module styles not found
ERROR: Python module gtkspellcheck not found
ERROR: Python module gi not found
ERROR: Python module helpers not found
ERROR: Python module helpers not found
ERROR: Python module remarkableconfig not found
ERROR: Python module Builder not found
ERROR: Python module helpers not found
ERROR: Python module Window not found
ERROR: Python module remarkableconfig not found
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    cmdclass={'install': InstallAndUpdateDataDirectory}
  File "/home/gurdit/Desktop/prjctUndrtkn/vvRemarkable/lib/python3.5/site-packages/DistUtilsExtra/auto.py", line 100, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/gurdit/Desktop/prjctUndrtkn/vvRemarkable/lib/python3.5/site-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python3.5/distutils/dist.py", line 253, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/usr/lib/python3.5/distutils/dist.py", line 1218, in set_provides
    distutils.versionpredicate.split_provision(v)
  File "/usr/lib/python3.5/distutils/versionpredicate.py", line 162, in split_provision
    raise ValueError("illegal provides specification: %r" % value)
ValueError: illegal provides specification: 'python-distutils-extra-2.39.DistUtilsExtra'
```
I am unable to solve out this problem. HELP NEEDED. :smile:

**Comment by tleb** [comment]
* You seem to be running using Python 3.5. Have you tried 2.7? 3.4?
* Is DistUtilsExtra a package which modifies some part of your Python install or is it standards? It seems like it's having troubles parsing its name.
* The error comes from [here](https://github.com/python/cpython/blob/3.5/Lib/distutils/versionpredicate.py) it seems.

I haven't tried building remarkable, so those are just guesses.

**Comment by gurditsbedi** [comment]
1. from my analysis python3 is required because in the "shebang !#" it is mentioned python 3
2. i have installed DistUtilsExtra package in the virtualenv
In the error report above

 ``` python
ERROR: Python module helpers not found  
ERROR: Python module helpers not found  
ERROR: Python module remarkableconfig not found  
ERROR: Python module Builder not found  
ERROR: Python module helpers not found  
ERROR: Python module Window not found  
ERROR: Python module remarkableconfig not found  
```
These are part of "remarkable" folder and "remarkable_lib" folder.

I request to try and build remarkable in a virtualenv.

**Comment by jamiemcg** [comment]
It is not yet possible to build from source.
The `setup.py`file is an artefact from using `Ubuntu Quickly`for packaging .deb files.

**Comment by gurditsbedi** [comment]
so if i want to contribute into the project and for it i have to test it, how can i?
