### ISSUE TITLE
Cannot export to HTML on Arch Linux

### ISSUE THREAD

**Issue by sergiodlc** [jamiemcg/Remarkable#69]
Installing Remarkable from the AUR leaves Remarkable unable to export to HTML. Upon exporting, the following exception is thrown:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/remarkable/RemarkableWindow.py", line 475, in on_menuitem_export_html_activate
    self.save_html(html)
  File "/usr/lib/python3.5/site-packages/remarkable/RemarkableWindow.py", line 510, in save_html
    soup = BeautifulSoup(html, "lxml")
  File "/usr/lib/python3.5/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

Once the exception is thrown, Remarkable becomes unresponsive. The Cancel button in the export dialog no longer works. The dialog can still be closed with `Esc`, but then the main window in Remarkable becomes unresponsive.

As shown in the exception message, the library `lxml` is missing. This happens because `python-lxml` is marked as an optional dependency of the package `python-beautifulsoup4` and thus is not installed by default. However, `python-lxml` is not optional for Remarkable, since it explicitly uses it.

A proper fix should include:

1. Listing `python-lxml` as a dependency in `aur/remarkable/PKGBUILD`.
2. Handling the exception so that Remarkable doesn't become unresponsive if the lxml library is not installed.

A pull request for this issue is on the way.

**Comment by sergiodlc** [comment]
OK, pull request created. I tested the changes in Arch and it works fine. Installing the package `python-lxml` does removes the exception. Even without the package installed, the exception is now shown in an error dialog. The exception handling code also takes care of IO errors (e.g. Trying to write a file without having write permissions in the target directory).
